import{a as q,S as M,i}from"./assets/vendor-DBgeciyq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();async function p(e,r){const t="https://pixabay.com/api/",o={key:"55161607-9b63bc502ca8d8d43be331324",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return console.log("Запрос с параметрами:",e,r),(await q.get(t,{params:o})).data}const s=document.querySelector(".gallery"),f=document.querySelector(".loader-wrap"),m=document.querySelector(".load-more-btn"),y=new M(".gallery a",{captionsData:"alt",captionDelay:250,scrollZoom:!1});function g(e){return e.map(({webformatURL:r,largeImageURL:l,tags:c,likes:t,views:o,comments:n,downloads:P})=>`<li class="gallery-item">
    <a href="${l}">
      <img class="image" src="${r}" alt="${c}" loading="lazy" />
    </a>
    <ul class="info-list">
      <li><p class="info-title">Likes</p><p class="info-text">${t}</p></li>
      <li><p class="info-title">Views</p><p class="info-text">${o}</p></li>
      <li><p class="info-title">Comments</p><p class="info-text">${n}</p></li>
      <li><p class="info-title">Downloads</p><p class="info-text">${P}</p></li>
    </ul>
  </li>`).join("")}function v(e){s&&(!e||e.length===0||(s.innerHTML=g(e),y.refresh()))}function B(e){s.insertAdjacentHTML("beforeend",g(e)),y.refresh()}function x(){const e=s==null?void 0:s.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}function E(){s&&(s.innerHTML="")}function L(){f&&f.classList.remove("is-hidden")}function b(){f&&f.classList.add("is-hidden")}function w(){m&&m.classList.remove("is-hidden")}function h(){m&&m.classList.add("is-hidden")}const u={searchForm:document.querySelector(".form"),searchInput:document.querySelector('.form input[name="search-text"]'),loader:document.querySelector(".loader-wrap"),loadMoreBtn:document.querySelector(".load-more-btn")};let d="",a=1;const S=15;u.searchForm.addEventListener("submit",async e=>{if(e.preventDefault(),d=u.searchInput.value.trim(),a=1,!d){i.warning({message:"Please enter a search query"});return}E(),h(),L();try{const r=await p(d,a);r.hits.length===0?(a=1,i.error({message:"Sorry, there are no images matching your search query. Please try again!"})):(v(r.hits),Math.ceil(r.totalHits/S)>1?w():i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a=1,i.error({message:"Error"});return}finally{b(),u.searchForm.reset()}});u.loadMoreBtn.addEventListener("click",async()=>{a+=1,h(),L();try{const e=await p(d,a);B(e.hits),x();const r=Math.ceil(e.totalHits/S);a>=r?(h(),i.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch{i.error({message:"Error"});return}finally{b()}});
//# sourceMappingURL=index.js.map
